### ISSUE TITLE
Latest version 0.6-1.20.1 incompatible with tetra

### ISSUE THREAD

**Issue by MishievousCloud** [kend1e/FANTASY-ARMOR#12]
I love this mod so much, it has the best armor out of any mods I have seen. 

I found an issue with the latest version being incompatible with tetra. The previous version of Fantasy Armor 0.5-1.20.1 works just fine with tetra and all the tetra add on mods i have in my custom modpack.

I have been narrowing down exactly which mod is having problems and it only occurs when I update this mod to the latest 0.6 version.

Current workaround is to revert back to 0.5-1.20.1.

Modloader: forge 1.20.1-47.3.5
tetra version: tetra-1.20.1-6.7.0

Here is a snippet of the crash log:

[Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:961) ~[client-1.20.1-20230612.114412-srg.jar%23831!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23831!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23831!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.5.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.5.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at se.mickelus.tetra.items.modular.impl.holo.gui.craft.HoloStatsGui.<clinit>(HoloStatsGui.java:26) ~[tetra-1.20.1-6.7.0.jar%23792!/:1.20.1-6.7.0]
	at se.mickelus.tetra.gui.stats.data.StatBarStore.m_6213_(StatBarStore.java:40) ~[tetra-1.20.1-6.7.0.jar%23792!/:1.20.1-6.7.0]
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15)

**Comment by kend1e** [comment]
Please update your Forge. The main mod constructor has been changed in newer versions of Forge, and the old version is marked as depricated
